language: python

sudo: required

cache: pip

python:
  - '2.7'
  - 'pypy'
  - '3.4'
  - '3.5'
  - '3.6'

before_install:
  - if [ "$ADAPTER" = 'oracle' ]; then
      wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.2.tar.gz' ;
      mkdir -p .travis/oracle ;
      tar x -C .travis/oracle --strip-components=1 -f v2.0.2.tar.gz ;
      bash -x .travis/oracle/download.sh ;
      bash -x .travis/oracle/install.sh ;
      pip install cx_Oracle ;
      echo -e "CREATE USER TEST IDENTIFIED BY TEST ;\n GRANT CONNECT, RESOURCE TO TEST ;\n" | "$ORACLE_HOME/bin/sqlplus" -L -S / AS SYSDBA ;
    fi

install:
  - pip install tox>=1.8

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_BASE=/u01/app/oracle
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - PATH=$PATH:$ORACLE_HOME/bin
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - NLS_LANG=American_America.UTF8
  matrix:
    - ADAPTER=oracle

matrix:
  exclude:
    - python: 'pypy'
      env: ADAPTER=postgres
    - python: 'pypy'
      env: ADAPTER=postgres3
    - python: 'pypy'
      env: ADAPTER=google
    - python: 'pypy'
      env: ADAPTER=oracle
    - python: '3.4'
      env: ADAPTER=google
    - python: '3.5'
      env: ADAPTER=google
    - python: '3.6'
      env: ADAPTER=google

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install codecov; fi
  - if [[ $ADAPTER == mongo ]]; then sleep 15; fi;
  - if [[ $ADAPTER == mysql ]]; then mysql -e 'create database pydal;'; fi
  - if [[ $ADAPTER == postgres* ]]; then psql -c 'create database pydal;' -U postgres; fi
  - if [[ $ADAPTER == postgres* ]]; then psql -c 'create extension postgis;' -U postgres -d pydal; fi
  - if [[ $ADAPTER == postgres* ]]; then psql -c 'SHOW SERVER_VERSION' -U postgres; fi

  # Install last sdk for app engine (update only whenever a new release is available)
  - if [[ $ADAPTER == google ]]; then wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.50.zip -nv; fi
  - if [[ $ADAPTER == google ]]; then unzip -q google_appengine_1.9.50.zip; fi
  - if [[ $ADAPTER == google ]]; then mv -f ./google_appengine/google ./google; fi


script:
  - if [[ $TRAVIS_PYTHON_VERSION != "2.7" ]]; then tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-$ADAPTER; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then tox -e coverage-$ADAPTER; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then codecov; fi

notifications:
  email: true

services:
  - mongodb
  - memcached

addons:
  postgresql: "9.4"

